/* AUTO-GENERATED by scripts/build-silhouettes.mjs — do not edit by hand.
 *
 * Which taxa have a PhyloPic silhouette in assets/silhouettes/, and the
 * licence each one carries. The tree draws these at the disc instead of a
 * photograph: nothing photographic survives 40px, and a silhouette is pure
 * shape, which is the one thing that does.
 *
 * Empty until the Silhouettes workflow has run — the resolver needs
 * api.phylopic.org, which the development sandbox cannot reach.
 */
export const SILHOUETTES = {};
