#!/usr/bin/env node
/**
 * Builds Kin's generated data from the answer key:
 *
 *   js/kin/bank.js      every generated question, "target.nearer.farther.surprise"
 *   js/kin/schedule.js  the daily calendar, one line per day
 *
 *   node scripts/kin-build.mjs              rebuild the bank; extend the calendar
 *   node scripts/kin-build.mjs --days 300   build the calendar out to Kin #300
 *
 * The calendar is history once a day can be played. Every day up to the last
 * one playable anywhere on Earth (UTC+14 is a day ahead of UTC) is copied from
 * the committed file unchanged; only later days are rebuilt, so adding
 * creatures or fixing the tree never alters a puzzle someone has played or
 * shared. scripts/kin-check-schedule.mjs enforces the same rule in CI.
 */
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { generateBank, buildSchedule, difficulty, REST_DAYS } from '../js/kin/generate.js';
import { QUESTIONS, CURATED_DAYS, HOOKS } from '../js/kin/questions.js';
import { resolve } from '../js/kin/key.js';
import { dateOfDay, weekdayOf, lastPlayableDay } from '../js/kin/calendar.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const opt = (name, fallback) => (argv.includes(`--${name}`) ? argv[argv.indexOf(`--${name}`) + 1] : fallback);

const SCHEDULE_FILE = path.join(ROOT, 'js/kin/schedule.js');
const BANK_FILE = path.join(ROOT, 'js/kin/bank.js');

const existing = existsSync(SCHEDULE_FILE)
  ? (await import(pathToFileURL(SCHEDULE_FILE).href)).SCHEDULE.map((line) => line.split(' '))
  : [];
const keepThrough = Math.max(CURATED_DAYS.length, lastPlayableDay());
const total = Math.max(Number(opt('days', 200)), existing.length, keepThrough);

// ── The bank ────────────────────────────────────────────────────────────────

const bank = generateBank({ curated: QUESTIONS });
const hooks = new Set(HOOKS);
const pool = [
  ...QUESTIONS.map((q) => ({ id: q.id, t: q.t, near: q.near, far: q.far, d: q.d, s: null, nearNode: resolve(q).nearNode, hook: hooks.has(q.id) })),
  ...bank.map((q) => ({ id: q.id, t: q.t, near: q.near, far: q.far, d: q.d, s: q.s, nearNode: q.nearNode, hook: false })),
];

const bankLines = bank.map((q) => `  '${q.id}.${q.s}',`).join('\n');
writeFileSync(BANK_FILE, `// GENERATED by scripts/kin-build.mjs from the answer key — do not edit by hand.
//
// Every question the tree can answer that is worth asking and that no
// hand-written question (js/kin/questions.js) already covers: one per target,
// near split and far split, with the most surprising pair of candidates.
// Each entry is "target.nearer.farther.surprise"; surprise > 0 means the wrong
// answer looks more like the target than the right one does. The why-line is
// the near split's line in js/kin/groups.js.
//
// ${bank.length} questions.
export const BANK = [
${bankLines}
];
`);

// ── The calendar ────────────────────────────────────────────────────────────

const days = buildSchedule({ existing, keepThrough, total, pool, curatedDays: CURATED_DAYS });
const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const dayLines = days.map((ids, i) => `  '${ids.join(' ')}', // #${i + 1} ${DOW[weekdayOf(i + 1)]} ${dateOfDay(i + 1)}`).join('\n');
writeFileSync(SCHEDULE_FILE, `// GENERATED by scripts/kin-build.mjs — do not edit by hand.
//
// Kin's calendar: the ten question ids for each day, Kin #1 first. A day that
// anyone can already be playing is history and never changes; CI compares
// this file with main and fails if one does (scripts/kin-check-schedule.mjs).
// Only days beyond that are rebuilt, so new creatures reach later puzzles
// without touching earlier ones.
//
// Days 1–${CURATED_DAYS.length} are hand-picked. After that: an opener whose answer surprises,
// then nine rising in difficulty — gentle on Mondays, hard on Saturdays, a
// themed set on Sundays — and no question again within ${REST_DAYS} days where the
// bank allows.
export const SCHEDULE = [
${dayLines}
];
`);

// ── Report ──────────────────────────────────────────────────────────────────

const byD = [1, 2, 3].map((d) => bank.filter((q) => difficulty(q.s) === d).length);
const used = new Set(days.flat());
console.log(`bank: ${bank.length} generated + ${QUESTIONS.length} hand-written (easy ${byD[0]} · medium ${byD[1]} · hard ${byD[2]})`);
console.log(`calendar: ${days.length} days; kept 1–${Math.min(keepThrough, existing.length || keepThrough)} as history; ${used.size} distinct questions used`);
