// ══════════════════════════════════════════════════════
// KIN — THE CREATURES
//
// Every leaf of js/kin/tree.js. Emoji stand in for the site's photographs
// and silhouettes in this test build: they need no credit line, load
// instantly, and read at a glance at any size. Photographs arrive with
// their credits in phase 2.
//
// Sentences are assembled from parts, so each language carries the forms
// its grammar needs:
//   en.n    name on the card        en.p   plural, used in "Whales and hippos…"
//   en.the  "the hippo" in "Yes, the hippo."
//   en.line "The hippo line branched off…" — the name in lower case unless
//           lower case would be wrong, as it is for "T. rex"
//   he.n    name on the card        he.def definite form, "ההיפופוטם"
//   he.le   with the preposition ל, "להיפופוטם", in "ללווייתן ולהיפופוטם היה…"
// `k` is the kingdom, which colours the dot on the card.
//
// Hebrew "you" is gendered, so the human card reads אנחנו ("us") in Hebrew.
// ══════════════════════════════════════════════════════

const c = (e, k, en, he) => ({ e, k, en, he });
const en = (n, p, the, line = n.toLowerCase()) => ({ n, p, the, line });
const he = (n, def, le) => ({ n, def, le });

export const CREATURES = {
  you:        c('🧑', 'animal', en('You', 'you', 'you'), he('אנחנו', 'אנחנו', 'לנו')),
  gorilla:    c('🦍', 'animal', en('Gorilla', 'gorillas', 'the gorilla'), he('גורילה', 'הגורילה', 'לגורילה')),
  orangutan:  c('🦧', 'animal', en('Orangutan', 'orangutans', 'the orangutan'), he('אורנגאוטן', 'האורנגאוטן', 'לאורנגאוטן')),
  monkey:     c('🐒', 'animal', en('Monkey', 'monkeys', 'the monkey'), he('קוף', 'הקוף', 'לקוף')),
  mouse:      c('🐁', 'animal', en('Mouse', 'mice', 'the mouse'), he('עכבר', 'העכבר', 'לעכבר')),
  hamster:    c('🐹', 'animal', en('Hamster', 'hamsters', 'the hamster'), he('אוגר', 'האוגר', 'לאוגר')),
  rat:        c('🐀', 'animal', en('Rat', 'rats', 'the rat'), he('חולדה', 'החולדה', 'לחולדה')),
  squirrel:   c('🐿️', 'animal', en('Squirrel', 'squirrels', 'the squirrel'), he('סנאי', 'הסנאי', 'לסנאי')),
  beaver:     c('🦫', 'animal', en('Beaver', 'beavers', 'the beaver'), he('בונה', 'הבונה', 'לבונה')),
  rabbit:     c('🐇', 'animal', en('Rabbit', 'rabbits', 'the rabbit'), he('ארנב', 'הארנב', 'לארנב')),
  hedgehog:   c('🦔', 'animal', en('Hedgehog', 'hedgehogs', 'the hedgehog'), he('קיפוד', 'הקיפוד', 'לקיפוד')),
  bat:        c('🦇', 'animal', en('Bat', 'bats', 'the bat'), he('עטלף', 'העטלף', 'לעטלף')),
  cat:        c('🐈', 'animal', en('Cat', 'cats', 'the cat'), he('חתול', 'החתול', 'לחתול')),
  lion:       c('🦁', 'animal', en('Lion', 'lions', 'the lion'), he('אריה', 'האריה', 'לאריה')),
  tiger:      c('🐅', 'animal', en('Tiger', 'tigers', 'the tiger'), he('טיגריס', 'הטיגריס', 'לטיגריס')),
  dog:        c('🐕', 'animal', en('Dog', 'dogs', 'the dog'), he('כלב', 'הכלב', 'לכלב')),
  fox:        c('🦊', 'animal', en('Fox', 'foxes', 'the fox'), he('שועל', 'השועל', 'לשועל')),
  bear:       c('🐻', 'animal', en('Bear', 'bears', 'the bear'), he('דוב', 'הדוב', 'לדוב')),
  panda:      c('🐼', 'animal', en('Panda', 'pandas', 'the panda'), he('פנדה', 'הפנדה', 'לפנדה')),
  seal:       c('🦭', 'animal', en('Seal', 'seals', 'the seal'), he('כלב ים', 'כלב הים', 'לכלב הים')),
  raccoon:    c('🦝', 'animal', en('Raccoon', 'raccoons', 'the raccoon'), he('דביבון', 'הדביבון', 'לדביבון')),
  otter:      c('🦦', 'animal', en('Otter', 'otters', 'the otter'), he('לוטרה', 'הלוטרה', 'ללוטרה')),
  badger:     c('🦡', 'animal', en('Badger', 'badgers', 'the badger'), he('גירית', 'הגירית', 'לגירית')),
  skunk:      c('🦨', 'animal', en('Skunk', 'skunks', 'the skunk'), he('בואש', 'הבואש', 'לבואש')),
  horse:      c('🐎', 'animal', en('Horse', 'horses', 'the horse'), he('סוס', 'הסוס', 'לסוס')),
  zebra:      c('🦓', 'animal', en('Zebra', 'zebras', 'the zebra'), he('זברה', 'הזברה', 'לזברה')),
  donkey:     c('🫏', 'animal', en('Donkey', 'donkeys', 'the donkey'), he('חמור', 'החמור', 'לחמור')),
  rhino:      c('🦏', 'animal', en('Rhino', 'rhinos', 'the rhino'), he('קרנף', 'הקרנף', 'לקרנף')),
  camel:      c('🐪', 'animal', en('Camel', 'camels', 'the camel'), he('גמל', 'הגמל', 'לגמל')),
  llama:      c('🦙', 'animal', en('Llama', 'llamas', 'the llama'), he('לאמה', 'הלאמה', 'ללאמה')),
  pig:        c('🐖', 'animal', en('Pig', 'pigs', 'the pig'), he('חזיר', 'החזיר', 'לחזיר')),
  giraffe:    c('🦒', 'animal', en('Giraffe', 'giraffes', 'the giraffe'), he("ג'ירפה", "הג'ירפה", "לג'ירפה")),
  cow:        c('🐄', 'animal', en('Cow', 'cows', 'the cow'), he('פרה', 'הפרה', 'לפרה')),
  sheep:      c('🐑', 'animal', en('Sheep', 'sheep', 'the sheep'), he('כבשה', 'הכבשה', 'לכבשה')),
  goat:       c('🐐', 'animal', en('Goat', 'goats', 'the goat'), he('עז', 'העז', 'לעז')),
  deer:       c('🦌', 'animal', en('Deer', 'deer', 'the deer'), he('אייל', 'האייל', 'לאייל')),
  hippo:      c('🦛', 'animal', en('Hippo', 'hippos', 'the hippo'), he('היפופוטם', 'ההיפופוטם', 'להיפופוטם')),
  whale:      c('🐳', 'animal', en('Whale', 'whales', 'the whale'), he('לווייתן', 'הלווייתן', 'ללווייתן')),
  dolphin:    c('🐬', 'animal', en('Dolphin', 'dolphins', 'the dolphin'), he('דולפין', 'הדולפין', 'לדולפין')),
  elephant:   c('🐘', 'animal', en('Elephant', 'elephants', 'the elephant'), he('פיל', 'הפיל', 'לפיל')),
  mammoth:    c('🦣', 'animal', en('Mammoth', 'mammoths', 'the mammoth'), he('ממותה', 'הממותה', 'לממותה')),
  koala:      c('🐨', 'animal', en('Koala', 'koalas', 'the koala'), he('קואלה', 'הקואלה', 'לקואלה')),
  kangaroo:   c('🦘', 'animal', en('Kangaroo', 'kangaroos', 'the kangaroo'), he('קנגורו', 'הקנגורו', 'לקנגורו')),
  sloth:      c('🦥', 'animal', en('Sloth', 'sloths', 'the sloth'), he('עצלן', 'העצלן', 'לעצלן')),
  chicken:    c('🐔', 'animal', en('Chicken', 'chickens', 'the chicken'), he('תרנגולת', 'התרנגולת', 'לתרנגולת')),
  turkey:     c('🦃', 'animal', en('Turkey', 'turkeys', 'the turkey'), he('תרנגול הודו', 'תרנגול ההודו', 'לתרנגול ההודו')),
  peacock:    c('🦚', 'animal', en('Peacock', 'peacocks', 'the peacock'), he('טווס', 'הטווס', 'לטווס')),
  duck:       c('🦆', 'animal', en('Duck', 'ducks', 'the duck'), he('ברווז', 'הברווז', 'לברווז')),
  swan:       c('🦢', 'animal', en('Swan', 'swans', 'the swan'), he('ברבור', 'הברבור', 'לברבור')),
  flamingo:   c('🦩', 'animal', en('Flamingo', 'flamingos', 'the flamingo'), he('פלמינגו', 'הפלמינגו', 'לפלמינגו')),
  pigeon:     c('🕊️', 'animal', en('Pigeon', 'pigeons', 'the pigeon'), he('יונה', 'היונה', 'ליונה')),
  dodo:       c('🦤', 'animal', en('Dodo', 'dodos', 'the dodo'), he('דודו', 'הדודו', 'לדודו')),
  penguin:    c('🐧', 'animal', en('Penguin', 'penguins', 'the penguin'), he('פינגווין', 'הפינגווין', 'לפינגווין')),
  eagle:      c('🦅', 'animal', en('Eagle', 'eagles', 'the eagle'), he('עיט', 'העיט', 'לעיט')),
  parrot:     c('🦜', 'animal', en('Parrot', 'parrots', 'the parrot'), he('תוכי', 'התוכי', 'לתוכי')),
  owl:        c('🦉', 'animal', en('Owl', 'owls', 'the owl'), he('ינשוף', 'הינשוף', 'לינשוף')),
  trex:       c('🦖', 'animal', en('T. rex', 'T. rex', 'T. rex', 'T. rex'), he('טירנוזאורוס', 'הטירנוזאורוס', 'לטירנוזאורוס')),
  sauropod:   c('🦕', 'animal', en('Brontosaurus', 'brontosaurs', 'the brontosaurus'), he('ברונטוזאורוס', 'הברונטוזאורוס', 'לברונטוזאורוס')),
  croc:       c('🐊', 'animal', en('Crocodile', 'crocodiles', 'the crocodile'), he('תנין', 'התנין', 'לתנין')),
  turtle:     c('🐢', 'animal', en('Turtle', 'turtles', 'the turtle'), he('צב', 'הצב', 'לצב')),
  gecko:      c('🦎', 'animal', en('Gecko', 'geckos', 'the gecko'), he('שממית', 'השממית', 'לשממית')),
  snake:      c('🐍', 'animal', en('Snake', 'snakes', 'the snake'), he('נחש', 'הנחש', 'לנחש')),
  frog:       c('🐸', 'animal', en('Frog', 'frogs', 'the frog'), he('צפרדע', 'הצפרדע', 'לצפרדע')),
  salmon:     c('🐟', 'animal', en('Salmon', 'salmon', 'the salmon'), he('סלמון', 'הסלמון', 'לסלמון')),
  shark:      c('🦈', 'animal', en('Shark', 'sharks', 'the shark'), he('כריש', 'הכריש', 'לכריש')),
  octopus:    c('🐙', 'animal', en('Octopus', 'octopuses', 'the octopus'), he('תמנון', 'התמנון', 'לתמנון')),
  jellyfish:  c('🪼', 'animal', en('Jellyfish', 'jellyfish', 'the jellyfish'), he('מדוזה', 'המדוזה', 'למדוזה')),
  coral:      c('🪸', 'animal', en('Coral', 'corals', 'the coral'), he('אלמוג', 'האלמוג', 'לאלמוג')),
  snail:      c('🐌', 'animal', en('Snail', 'snails', 'the snail'), he('חילזון', 'החילזון', 'לחילזון')),
  lobster:    c('🦞', 'animal', en('Lobster', 'lobsters', 'the lobster'), he('לובסטר', 'הלובסטר', 'ללובסטר')),
  crab:       c('🦀', 'animal', en('Crab', 'crabs', 'the crab'), he('סרטן', 'הסרטן', 'לסרטן')),
  bee:        c('🐝', 'animal', en('Bee', 'bees', 'the bee'), he('דבורה', 'הדבורה', 'לדבורה')),
  ant:        c('🐜', 'animal', en('Ant', 'ants', 'the ant'), he('נמלה', 'הנמלה', 'לנמלה')),
  butterfly:  c('🦋', 'animal', en('Butterfly', 'butterflies', 'the butterfly'), he('פרפר', 'הפרפר', 'לפרפר')),
  mosquito:   c('🦟', 'animal', en('Mosquito', 'mosquitoes', 'the mosquito'), he('יתוש', 'היתוש', 'ליתוש')),
  fly:        c('🪰', 'animal', en('Fly', 'flies', 'the fly'), he('זבוב', 'הזבוב', 'לזבוב')),
  spider:     c('🕷️', 'animal', en('Spider', 'spiders', 'the spider'), he('עכביש', 'העכביש', 'לעכביש')),
  scorpion:   c('🦂', 'animal', en('Scorpion', 'scorpions', 'the scorpion'), he('עקרב', 'העקרב', 'לעקרב')),
  mushroom:   c('🍄', 'fungus', en('Mushroom', 'mushrooms', 'the mushroom'), he('פטרייה', 'הפטרייה', 'לפטרייה')),
  daisy:      c('🌼', 'plant', en('Daisy', 'daisies', 'the daisy'), he('חיננית', 'החיננית', 'לחיננית')),
  sunflower:  c('🌻', 'plant', en('Sunflower', 'sunflowers', 'the sunflower'), he('חמנייה', 'החמנייה', 'לחמנייה')),
  lettuce:    c('🥬', 'plant', en('Lettuce', 'lettuce', 'lettuce'), he('חסה', 'החסה', 'לחסה')),
  carrot:     c('🥕', 'plant', en('Carrot', 'carrots', 'the carrot'), he('גזר', 'הגזר', 'לגזר')),
  coffee:     c('☕', 'plant', en('Coffee', 'coffee plants', 'coffee'), he('קפה', 'הקפה', 'לקפה')),
  olive:      c('🫒', 'plant', en('Olive', 'olives', 'the olive'), he('זית', 'הזית', 'לזית')),
  tomato:     c('🍅', 'plant', en('Tomato', 'tomatoes', 'the tomato'), he('עגבנייה', 'העגבנייה', 'לעגבנייה')),
  potato:     c('🥔', 'plant', en('Potato', 'potatoes', 'the potato'), he('תפוח אדמה', 'תפוח האדמה', 'לתפוח האדמה')),
  eggplant:   c('🍆', 'plant', en('Eggplant', 'eggplants', 'the eggplant'), he('חציל', 'החציל', 'לחציל')),
  chili:      c('🌶️', 'plant', en('Chili pepper', 'chili peppers', 'the chili pepper'), he('פלפל חריף', 'הפלפל החריף', 'לפלפל החריף')),
  sweetpotato: c('🍠', 'plant', en('Sweet potato', 'sweet potatoes', 'the sweet potato'), he('בטטה', 'הבטטה', 'לבטטה')),
  kiwi:       c('🥝', 'plant', en('Kiwifruit', 'kiwifruit', 'the kiwifruit'), he('קיווי', 'הקיווי', 'לקיווי')),
  blueberry:  c('🫐', 'plant', en('Blueberry', 'blueberries', 'the blueberry'), he('אוכמנית', 'האוכמנית', 'לאוכמנית')),
  cactus:     c('🌵', 'plant', en('Cactus', 'cacti', 'the cactus'), he('קקטוס', 'הקקטוס', 'לקקטוס')),
  pine:       c('🌲', 'plant', en('Pine', 'pines', 'the pine'), he('אורן', 'האורן', 'לאורן')),
  avocado:    c('🥑', 'plant', en('Avocado', 'avocados', 'the avocado'), he('אבוקדו', 'האבוקדו', 'לאבוקדו')),
  rose:       c('🌹', 'plant', en('Rose', 'roses', 'the rose'), he('ורד', 'הוורד', 'לוורד')),
  strawberry: c('🍓', 'plant', en('Strawberry', 'strawberries', 'the strawberry'), he('תות', 'התות', 'לתות')),
  apple:      c('🍎', 'plant', en('Apple', 'apples', 'the apple'), he('תפוח', 'התפוח', 'לתפוח')),
  cherry:     c('🍒', 'plant', en('Cherry', 'cherries', 'the cherry'), he('דובדבן', 'הדובדבן', 'לדובדבן')),
  peach:      c('🍑', 'plant', en('Peach', 'peaches', 'the peach'), he('אפרסק', 'האפרסק', 'לאפרסק')),
  cucumber:   c('🥒', 'plant', en('Cucumber', 'cucumbers', 'the cucumber'), he('מלפפון', 'המלפפון', 'למלפפון')),
  melon:      c('🍈', 'plant', en('Melon', 'melons', 'the melon'), he('מלון', 'המלון', 'למלון')),
  pea:        c('🫛', 'plant', en('Pea', 'peas', 'the pea'), he('אפונה', 'האפונה', 'לאפונה')),
  peanut:     c('🥜', 'plant', en('Peanut', 'peanuts', 'the peanut'), he('בוטן', 'הבוטן', 'לבוטן')),
  chestnut:   c('🌰', 'plant', en('Chestnut', 'chestnuts', 'the chestnut'), he('ערמון', 'הערמון', 'לערמון')),
  watermelon: c('🍉', 'plant', en('Watermelon', 'watermelons', 'the watermelon'), he('אבטיח', 'האבטיח', 'לאבטיח')),
  orange:     c('🍊', 'plant', en('Orange', 'oranges', 'the orange'), he('תפוז', 'התפוז', 'לתפוז')),
  lemon:      c('🍋', 'plant', en('Lemon', 'lemons', 'the lemon'), he('לימון', 'הלימון', 'ללימון')),
  mango:      c('🥭', 'plant', en('Mango', 'mangoes', 'the mango'), he('מנגו', 'המנגו', 'למנגו')),
  maple:      c('🍁', 'plant', en('Maple', 'maples', 'the maple'), he('אדר', 'האדר', 'לאדר')),
  choc:       c('🍫', 'plant', en('Chocolate', 'cocoa trees', 'chocolate'), he('שוקולד', 'השוקולד', 'לשוקולד')),
  hibiscus:   c('🌺', 'plant', en('Hibiscus', 'hibiscus', 'the hibiscus'), he('היביסקוס', 'ההיביסקוס', 'להיביסקוס')),
  broccoli:   c('🥦', 'plant', en('Broccoli', 'broccoli', 'broccoli'), he('ברוקולי', 'הברוקולי', 'לברוקולי')),
  grape:      c('🍇', 'plant', en('Grapes', 'grapes', 'the grape'), he('ענבים', 'הענבים', 'לענבים')),
  tulip:      c('🌷', 'plant', en('Tulip', 'tulips', 'the tulip'), he('צבעוני', 'הצבעוני', 'לצבעוני')),
  palm:       c('🌴', 'plant', en('Palm', 'palms', 'the palm'), he('דקל', 'הדקל', 'לדקל')),
  banana:     c('🍌', 'plant', en('Banana', 'bananas', 'the banana'), he('בננה', 'הבננה', 'לבננה')),
  ginger:     c('🫚', 'plant', en('Ginger', 'ginger', 'ginger'), he("ג'ינג'ר", "הג'ינג'ר", "לג'ינג'ר")),
  pineapple:  c('🍍', 'plant', en('Pineapple', 'pineapples', 'the pineapple'), he('אננס', 'האננס', 'לאננס')),
  rice:       c('🌾', 'plant', en('Rice', 'rice', 'rice'), he('אורז', 'האורז', 'לאורז')),
  corn:       c('🌽', 'plant', en('Corn', 'corn', 'corn'), he('תירס', 'התירס', 'לתירס')),
  bamboo:     c('🎋', 'plant', en('Bamboo', 'bamboo', 'bamboo'), he('במבוק', 'הבמבוק', 'לבמבוק')),
};

/*
 * What a casual player lumps each creature with — its look, its habitat, the
 * aisle it is sold in — not what it is. Only the question generator reads
 * this (js/kin/generate.js): a question is hard when the wrong answer shares
 * more of these with the target than the right one does, as the shark does
 * with the whale and the hippo does not. The mushroom is tagged "plant" on
 * purpose; that is the belief the game exists to overturn.
 */
export const LOOKS = {
  you: 'human',
  gorilla: 'ape furry wild big', orangutan: 'ape furry wild',
  monkey: 'ape furry wild',
  mouse: 'furry small pet rodentlike', hamster: 'furry small pet rodentlike',
  rat: 'furry small rodentlike', squirrel: 'furry small wild rodentlike',
  beaver: 'furry water wild',
  rabbit: 'furry small pet rodentlike', hedgehog: 'furry small rodentlike wild',
  bat: 'furry small flyer night wild',
  cat: 'furry pet hunter', dog: 'furry pet hunter', bear: 'furry wild big hunter',
  lion: 'furry wild big hunter', tiger: 'furry wild big hunter striped', fox: 'furry wild hunter',
  panda: 'furry wild big', badger: 'furry wild night striped', skunk: 'furry wild night small striped',
  seal: 'sea water wild', raccoon: 'furry wild night striped', otter: 'furry water wild',
  horse: 'hoofed farm big', rhino: 'hoofed wild big horned', camel: 'hoofed farm big desert',
  zebra: 'hoofed wild striped', donkey: 'hoofed farm', llama: 'hoofed farm furry',
  pig: 'hoofed farm', giraffe: 'hoofed wild big', cow: 'hoofed farm big horned',
  sheep: 'hoofed farm furry', goat: 'hoofed farm horned', deer: 'hoofed wild horned',
  hippo: 'wild big water',
  whale: 'sea water big fishlike', dolphin: 'sea water fishlike',
  elephant: 'wild big trunk', mammoth: 'big trunk extinct',
  koala: 'furry wild climber', kangaroo: 'furry wild', sloth: 'furry wild climber',
  chicken: 'bird farm', turkey: 'bird farm', peacock: 'bird farm',
  duck: 'bird farm water', swan: 'bird wild water', flamingo: 'bird wild water',
  pigeon: 'bird flyer', dodo: 'bird extinct', penguin: 'bird sea water',
  eagle: 'bird flyer hunter wild', parrot: 'bird flyer pet', owl: 'bird flyer hunter wild night',
  trex: 'reptile extinct hunter big scaly', sauropod: 'reptile extinct big scaly',
  croc: 'reptile scaly water hunter',
  turtle: 'reptile shell water', gecko: 'reptile scaly small', snake: 'reptile scaly legless',
  frog: 'water small slimy',
  salmon: 'fish fishlike sea water', shark: 'fish fishlike sea water hunter',
  octopus: 'sea water', snail: 'shell slimy small',
  jellyfish: 'sea water slimy', coral: 'sea plant',
  lobster: 'sea shell seafood clawed', crab: 'sea shell seafood clawed',
  bee: 'bug flyer small', ant: 'bug small', butterfly: 'bug flyer small',
  mosquito: 'bug flyer small', fly: 'bug flyer small',
  spider: 'bug small eightlegs', scorpion: 'bug eightlegs desert clawed',
  mushroom: 'plant veg',
  daisy: 'plant flower', sunflower: 'plant flower', rose: 'plant flower red', tulip: 'plant flower',
  lettuce: 'plant veg leafy', broccoli: 'plant veg leafy', tomato: 'plant veg red',
  potato: 'plant veg root', sweetpotato: 'plant veg root', carrot: 'plant veg root',
  ginger: 'plant veg root spicy', chili: 'plant veg red spicy', eggplant: 'plant veg',
  cucumber: 'plant veg', pea: 'plant veg',
  peanut: 'plant nut', chestnut: 'plant nut tree',
  corn: 'plant grain veg', rice: 'plant grain', bamboo: 'plant tree',
  kiwi: 'plant fruit', blueberry: 'plant fruit berry', strawberry: 'plant fruit berry red',
  apple: 'plant fruit tree red', cherry: 'plant fruit tree red stone', peach: 'plant fruit tree stone',
  mango: 'plant fruit tree stone', olive: 'plant fruit tree stone', avocado: 'plant fruit tree',
  watermelon: 'plant fruit', melon: 'plant fruit', orange: 'plant fruit tree', lemon: 'plant fruit tree',
  grape: 'plant fruit', banana: 'plant fruit', pineapple: 'plant fruit',
  coffee: 'plant drink', choc: 'plant drink sweet tree',
  hibiscus: 'plant flower red',
  cactus: 'plant desert', maple: 'plant tree', palm: 'plant tree', pine: 'plant tree',
};

/*
 * One species stands for each creature wherever a name has to be looked up
 * elsewhere — Open Tree of Life for the topology check
 * (scripts/kin-check-opentree.mjs), and later photographs and credits. The
 * choice matters: the game's "gecko" is a gecko, and which lizard you pick
 * changes where a snake meets it.
 */
export const SPECIES = {
  you: 'Homo sapiens', gorilla: 'Gorilla gorilla', orangutan: 'Pongo abelii', monkey: 'Macaca mulatta',
  mouse: 'Mus musculus', rat: 'Rattus norvegicus', hamster: 'Mesocricetus auratus',
  squirrel: 'Sciurus vulgaris', beaver: 'Castor fiber', rabbit: 'Oryctolagus cuniculus',
  hedgehog: 'Erinaceus europaeus', bat: 'Rousettus aegyptiacus',
  cat: 'Felis catus', lion: 'Panthera leo', tiger: 'Panthera tigris',
  dog: 'Canis lupus', fox: 'Vulpes vulpes', bear: 'Ursus arctos', panda: 'Ailuropoda melanoleuca',
  seal: 'Phoca vitulina', raccoon: 'Procyon lotor', otter: 'Lutra lutra', badger: 'Meles meles',
  skunk: 'Mephitis mephitis',
  horse: 'Equus caballus', zebra: 'Equus quagga', donkey: 'Equus asinus', rhino: 'Ceratotherium simum',
  camel: 'Camelus dromedarius', llama: 'Lama glama', pig: 'Sus scrofa',
  giraffe: 'Giraffa camelopardalis', deer: 'Cervus elaphus', cow: 'Bos taurus', sheep: 'Ovis aries',
  goat: 'Capra hircus', hippo: 'Hippopotamus amphibius', whale: 'Balaenoptera musculus',
  dolphin: 'Tursiops truncatus', elephant: 'Loxodonta africana', mammoth: 'Mammuthus primigenius',
  sloth: 'Bradypus variegatus', koala: 'Phascolarctos cinereus', kangaroo: 'Macropus giganteus',
  chicken: 'Gallus gallus', turkey: 'Meleagris gallopavo', peacock: 'Pavo cristatus',
  duck: 'Anas platyrhynchos', swan: 'Cygnus olor', flamingo: 'Phoenicopterus roseus',
  pigeon: 'Columba livia', dodo: 'Raphus cucullatus', penguin: 'Aptenodytes forsteri',
  eagle: 'Aquila chrysaetos', parrot: 'Ara macao', owl: 'Bubo bubo',
  trex: 'Tyrannosaurus rex', sauropod: 'Brontosaurus excelsus', croc: 'Crocodylus porosus',
  turtle: 'Chelonia mydas', gecko: 'Hemidactylus turcicus', snake: 'Python bivittatus',
  frog: 'Rana temporaria', salmon: 'Salmo salar', shark: 'Carcharodon carcharias',
  octopus: 'Octopus vulgaris', snail: 'Cornu aspersum', jellyfish: 'Aurelia aurita',
  coral: 'Acropora millepora',
  lobster: 'Homarus americanus', crab: 'Callinectes sapidus', bee: 'Apis mellifera',
  ant: 'Formica rufa', butterfly: 'Danaus plexippus', mosquito: 'Aedes aegypti',
  fly: 'Musca domestica', spider: 'Araneus diadematus', scorpion: 'Centruroides sculpturatus',
  mushroom: 'Agaricus bisporus',
  daisy: 'Bellis perennis', sunflower: 'Helianthus annuus', lettuce: 'Lactuca sativa',
  carrot: 'Daucus carota', coffee: 'Coffea arabica', olive: 'Olea europaea',
  tomato: 'Solanum lycopersicum', potato: 'Solanum tuberosum', eggplant: 'Solanum melongena',
  chili: 'Capsicum annuum', sweetpotato: 'Ipomoea batatas',
  kiwi: 'Actinidia chinensis', blueberry: 'Vaccinium corymbosum', cactus: 'Carnegiea gigantea',
  rose: 'Rosa canina', strawberry: 'Fragaria vesca', apple: 'Malus domestica',
  cherry: 'Prunus avium', peach: 'Prunus persica',
  cucumber: 'Cucumis sativus', melon: 'Cucumis melo', watermelon: 'Citrullus lanatus',
  pea: 'Pisum sativum', peanut: 'Arachis hypogaea',
  chestnut: 'Castanea sativa',
  orange: 'Citrus sinensis', lemon: 'Citrus limon', mango: 'Mangifera indica', maple: 'Acer saccharum',
  choc: 'Theobroma cacao', hibiscus: 'Hibiscus rosa-sinensis', broccoli: 'Brassica oleracea',
  grape: 'Vitis vinifera', pine: 'Pinus sylvestris', avocado: 'Persea americana',
  tulip: 'Tulipa gesneriana', palm: 'Phoenix dactylifera', banana: 'Musa acuminata',
  ginger: 'Zingiber officinale', pineapple: 'Ananas comosus',
  rice: 'Oryza sativa', corn: 'Zea mays', bamboo: 'Phyllostachys edulis',
};
