// ══════════════════════════════════════════════════════
// KIN — THE CREATURES
//
// Every leaf of js/kin/tree.js. Emoji stand in for the site's photographs
// and silhouettes in this test build: they need no credit line, load
// instantly, and read at a glance at any size. Photographs arrive with
// their credits in phase 2.
//
// Sentences are assembled from parts, so each language carries the forms
// its grammar needs:
//   en.n    name on the card        en.p   plural, used in "Whales and hippos…"
//   en.the  "the hippo" in "Yes, the hippo."
//   en.line "The hippo line branched off…" — the name in lower case unless
//           lower case would be wrong, as it is for "T. rex"
//   he.n    name on the card        he.def definite form, "ההיפופוטם"
//   he.le   with the preposition ל, "להיפופוטם", in "ללווייתן ולהיפופוטם היה…"
//   ru.n    name on the card        ru.the "✓ Да, бегемот." (lower case)
//   ru.g    genitive singular, in "Последний общий предок кита и бегемота…"
//   ru.line genitive after "Предки…": plural where Russian counts the thing,
//           "Предки акул", and singular where it does not, "Предки риса"
// `k` is the kingdom, which colours the dot on the card.
//
// Hebrew "you" is gendered, so the human card reads אנחנו ("us") in Hebrew,
// and Russian follows it with Мы: "С кем мы в более близком родстве?" In a
// Russian sentence the human is человека, as in the textbook "общий предок
// человека и шимпанзе".
//
// A few Russian names are narrower than the English, because the English
// word would mislead: the rhesus macaque is Макака, since обезьяна also
// covers the gorilla it is being compared with; the sweet cherry is Черешня
// and the highbush blueberry Голубика, which are those species' own names;
// and the apple is the tree, Яблоня, because an яблоко has no ancestors.
// ══════════════════════════════════════════════════════

const c = (e, k, en, he, ru) => ({ e, k, en, he, ru });
const en = (n, p, the, line = n.toLowerCase()) => ({ n, p, the, line });
const he = (n, def, le) => ({ n, def, le });
const ru = (n, g, line = g, the = n.toLowerCase()) => ({ n, g, line, the });

export const CREATURES = {
  you:        c('🧑', 'animal', en('You', 'you', 'you'), he('אנחנו', 'אנחנו', 'לנו'),
                ru('Мы', 'человека', 'людей')),
  gorilla:    c('🦍', 'animal', en('Gorilla', 'gorillas', 'the gorilla'), he('גורילה', 'הגורילה', 'לגורילה'),
                ru('Горилла', 'гориллы', 'горилл')),
  orangutan:  c('🦧', 'animal', en('Orangutan', 'orangutans', 'the orangutan'), he('אורנגאוטן', 'האורנגאוטן', 'לאורנגאוטן'),
                ru('Орангутан', 'орангутана', 'орангутанов')),
  monkey:     c('🐒', 'animal', en('Monkey', 'monkeys', 'the monkey'), he('קוף', 'הקוף', 'לקוף'),
                ru('Макака', 'макаки', 'макак')),
  mouse:      c('🐁', 'animal', en('Mouse', 'mice', 'the mouse'), he('עכבר', 'העכבר', 'לעכבר'),
                ru('Мышь', 'мыши', 'мышей')),
  hamster:    c('🐹', 'animal', en('Hamster', 'hamsters', 'the hamster'), he('אוגר', 'האוגר', 'לאוגר'),
                ru('Хомяк', 'хомяка', 'хомяков')),
  rat:        c('🐀', 'animal', en('Rat', 'rats', 'the rat'), he('חולדה', 'החולדה', 'לחולדה'),
                ru('Крыса', 'крысы', 'крыс')),
  squirrel:   c('🐿️', 'animal', en('Squirrel', 'squirrels', 'the squirrel'), he('סנאי', 'הסנאי', 'לסנאי'),
                ru('Белка', 'белки', 'белок')),
  beaver:     c('🦫', 'animal', en('Beaver', 'beavers', 'the beaver'), he('בונה', 'הבונה', 'לבונה'),
                ru('Бобр', 'бобра', 'бобров')),
  rabbit:     c('🐇', 'animal', en('Rabbit', 'rabbits', 'the rabbit'), he('ארנב', 'הארנב', 'לארנב'),
                ru('Кролик', 'кролика', 'кроликов')),
  hedgehog:   c('🦔', 'animal', en('Hedgehog', 'hedgehogs', 'the hedgehog'), he('קיפוד', 'הקיפוד', 'לקיפוד'),
                ru('Ёж', 'ежа', 'ежей')),
  bat:        c('🦇', 'animal', en('Bat', 'bats', 'the bat'), he('עטלף', 'העטלף', 'לעטלף'),
                ru('Летучая мышь', 'летучей мыши', 'летучих мышей')),
  cat:        c('🐈', 'animal', en('Cat', 'cats', 'the cat'), he('חתול', 'החתול', 'לחתול'),
                ru('Кошка', 'кошки', 'кошек')),
  lion:       c('🦁', 'animal', en('Lion', 'lions', 'the lion'), he('אריה', 'האריה', 'לאריה'),
                ru('Лев', 'льва', 'львов')),
  tiger:      c('🐅', 'animal', en('Tiger', 'tigers', 'the tiger'), he('טיגריס', 'הטיגריס', 'לטיגריס'),
                ru('Тигр', 'тигра', 'тигров')),
  dog:        c('🐕', 'animal', en('Dog', 'dogs', 'the dog'), he('כלב', 'הכלב', 'לכלב'),
                ru('Собака', 'собаки', 'собак')),
  fox:        c('🦊', 'animal', en('Fox', 'foxes', 'the fox'), he('שועל', 'השועל', 'לשועל'),
                ru('Лиса', 'лисы', 'лис')),
  bear:       c('🐻', 'animal', en('Bear', 'bears', 'the bear'), he('דוב', 'הדוב', 'לדוב'),
                ru('Медведь', 'медведя', 'медведей')),
  panda:      c('🐼', 'animal', en('Panda', 'pandas', 'the panda'), he('פנדה', 'הפנדה', 'לפנדה'),
                ru('Панда', 'панды', 'панд')),
  seal:       c('🦭', 'animal', en('Seal', 'seals', 'the seal'), he('כלב ים', 'כלב הים', 'לכלב הים'),
                ru('Тюлень', 'тюленя', 'тюленей')),
  raccoon:    c('🦝', 'animal', en('Raccoon', 'raccoons', 'the raccoon'), he('דביבון', 'הדביבון', 'לדביבון'),
                ru('Енот', 'енота', 'енотов')),
  otter:      c('🦦', 'animal', en('Otter', 'otters', 'the otter'), he('לוטרה', 'הלוטרה', 'ללוטרה'),
                ru('Выдра', 'выдры', 'выдр')),
  badger:     c('🦡', 'animal', en('Badger', 'badgers', 'the badger'), he('גירית', 'הגירית', 'לגירית'),
                ru('Барсук', 'барсука', 'барсуков')),
  skunk:      c('🦨', 'animal', en('Skunk', 'skunks', 'the skunk'), he('בואש', 'הבואש', 'לבואש'),
                ru('Скунс', 'скунса', 'скунсов')),
  horse:      c('🐎', 'animal', en('Horse', 'horses', 'the horse'), he('סוס', 'הסוס', 'לסוס'),
                ru('Лошадь', 'лошади', 'лошадей')),
  zebra:      c('🦓', 'animal', en('Zebra', 'zebras', 'the zebra'), he('זברה', 'הזברה', 'לזברה'),
                ru('Зебра', 'зебры', 'зебр')),
  donkey:     c('🫏', 'animal', en('Donkey', 'donkeys', 'the donkey'), he('חמור', 'החמור', 'לחמור'),
                ru('Осёл', 'осла', 'ослов')),
  rhino:      c('🦏', 'animal', en('Rhino', 'rhinos', 'the rhino'), he('קרנף', 'הקרנף', 'לקרנף'),
                ru('Носорог', 'носорога', 'носорогов')),
  camel:      c('🐪', 'animal', en('Camel', 'camels', 'the camel'), he('גמל', 'הגמל', 'לגמל'),
                ru('Верблюд', 'верблюда', 'верблюдов')),
  llama:      c('🦙', 'animal', en('Llama', 'llamas', 'the llama'), he('לאמה', 'הלאמה', 'ללאמה'),
                ru('Лама', 'ламы', 'лам')),
  pig:        c('🐖', 'animal', en('Pig', 'pigs', 'the pig'), he('חזיר', 'החזיר', 'לחזיר'),
                ru('Свинья', 'свиньи', 'свиней')),
  giraffe:    c('🦒', 'animal', en('Giraffe', 'giraffes', 'the giraffe'), he("ג'ירפה", "הג'ירפה", "לג'ירפה"),
                ru('Жираф', 'жирафа', 'жирафов')),
  cow:        c('🐄', 'animal', en('Cow', 'cows', 'the cow'), he('פרה', 'הפרה', 'לפרה'),
                ru('Корова', 'коровы', 'коров')),
  sheep:      c('🐑', 'animal', en('Sheep', 'sheep', 'the sheep'), he('כבשה', 'הכבשה', 'לכבשה'),
                ru('Овца', 'овцы', 'овец')),
  goat:       c('🐐', 'animal', en('Goat', 'goats', 'the goat'), he('עז', 'העז', 'לעז'),
                ru('Коза', 'козы', 'коз')),
  deer:       c('🦌', 'animal', en('Deer', 'deer', 'the deer'), he('אייל', 'האייל', 'לאייל'),
                ru('Олень', 'оленя', 'оленей')),
  hippo:      c('🦛', 'animal', en('Hippo', 'hippos', 'the hippo'), he('היפופוטם', 'ההיפופוטם', 'להיפופוטם'),
                ru('Бегемот', 'бегемота', 'бегемотов')),
  whale:      c('🐳', 'animal', en('Whale', 'whales', 'the whale'), he('לווייתן', 'הלווייתן', 'ללווייתן'),
                ru('Кит', 'кита', 'китов')),
  dolphin:    c('🐬', 'animal', en('Dolphin', 'dolphins', 'the dolphin'), he('דולפין', 'הדולפין', 'לדולפין'),
                ru('Дельфин', 'дельфина', 'дельфинов')),
  elephant:   c('🐘', 'animal', en('Elephant', 'elephants', 'the elephant'), he('פיל', 'הפיל', 'לפיל'),
                ru('Слон', 'слона', 'слонов')),
  mammoth:    c('🦣', 'animal', en('Mammoth', 'mammoths', 'the mammoth'), he('ממותה', 'הממותה', 'לממותה'),
                ru('Мамонт', 'мамонта', 'мамонтов')),
  koala:      c('🐨', 'animal', en('Koala', 'koalas', 'the koala'), he('קואלה', 'הקואלה', 'לקואלה'),
                ru('Коала', 'коалы', 'коал')),
  kangaroo:   c('🦘', 'animal', en('Kangaroo', 'kangaroos', 'the kangaroo'), he('קנגורו', 'הקנגורו', 'לקנגורו'),
                ru('Кенгуру', 'кенгуру')),
  sloth:      c('🦥', 'animal', en('Sloth', 'sloths', 'the sloth'), he('עצלן', 'העצלן', 'לעצלן'),
                ru('Ленивец', 'ленивца', 'ленивцев')),
  chicken:    c('🐔', 'animal', en('Chicken', 'chickens', 'the chicken'), he('תרנגולת', 'התרנגולת', 'לתרנגולת'),
                ru('Курица', 'курицы', 'кур')),
  turkey:     c('🦃', 'animal', en('Turkey', 'turkeys', 'the turkey'), he('תרנגול הודו', 'תרנגול ההודו', 'לתרנגול ההודו'),
                ru('Индейка', 'индейки', 'индеек')),
  peacock:    c('🦚', 'animal', en('Peacock', 'peacocks', 'the peacock'), he('טווס', 'הטווס', 'לטווס'),
                ru('Павлин', 'павлина', 'павлинов')),
  duck:       c('🦆', 'animal', en('Duck', 'ducks', 'the duck'), he('ברווז', 'הברווז', 'לברווז'),
                ru('Утка', 'утки', 'уток')),
  swan:       c('🦢', 'animal', en('Swan', 'swans', 'the swan'), he('ברבור', 'הברבור', 'לברבור'),
                ru('Лебедь', 'лебедя', 'лебедей')),
  flamingo:   c('🦩', 'animal', en('Flamingo', 'flamingos', 'the flamingo'), he('פלמינגו', 'הפלמינגו', 'לפלמינגו'),
                ru('Фламинго', 'фламинго')),
  pigeon:     c('🕊️', 'animal', en('Pigeon', 'pigeons', 'the pigeon'), he('יונה', 'היונה', 'ליונה'),
                ru('Голубь', 'голубя', 'голубей')),
  dodo:       c('🦤', 'animal', en('Dodo', 'dodos', 'the dodo'), he('דודו', 'הדודו', 'לדודו'),
                ru('Додо', 'додо')),
  penguin:    c('🐧', 'animal', en('Penguin', 'penguins', 'the penguin'), he('פינגווין', 'הפינגווין', 'לפינגווין'),
                ru('Пингвин', 'пингвина', 'пингвинов')),
  eagle:      c('🦅', 'animal', en('Eagle', 'eagles', 'the eagle'), he('עיט', 'העיט', 'לעיט'),
                ru('Орёл', 'орла', 'орлов')),
  parrot:     c('🦜', 'animal', en('Parrot', 'parrots', 'the parrot'), he('תוכי', 'התוכי', 'לתוכי'),
                ru('Попугай', 'попугая', 'попугаев')),
  owl:        c('🦉', 'animal', en('Owl', 'owls', 'the owl'), he('ינשוף', 'הינשוף', 'לינשוף'),
                ru('Сова', 'совы', 'сов')),
  trex:       c('🦖', 'animal', en('T. rex', 'T. rex', 'T. rex', 'T. rex'), he('טירנוזאורוס', 'הטירנוזאורוס', 'לטירנוזאורוס'),
                ru('Тираннозавр', 'тираннозавра', 'тираннозавров')),
  sauropod:   c('🦕', 'animal', en('Brontosaurus', 'brontosaurs', 'the brontosaurus'), he('ברונטוזאורוס', 'הברונטוזאורוס', 'לברונטוזאורוס'),
                ru('Бронтозавр', 'бронтозавра', 'бронтозавров')),
  croc:       c('🐊', 'animal', en('Crocodile', 'crocodiles', 'the crocodile'), he('תנין', 'התנין', 'לתנין'),
                ru('Крокодил', 'крокодила', 'крокодилов')),
  turtle:     c('🐢', 'animal', en('Turtle', 'turtles', 'the turtle'), he('צב', 'הצב', 'לצב'),
                ru('Черепаха', 'черепахи', 'черепах')),
  gecko:      c('🦎', 'animal', en('Gecko', 'geckos', 'the gecko'), he('שממית', 'השממית', 'לשממית'),
                ru('Геккон', 'геккона', 'гекконов')),
  snake:      c('🐍', 'animal', en('Snake', 'snakes', 'the snake'), he('נחש', 'הנחש', 'לנחש'),
                ru('Змея', 'змеи', 'змей')),
  frog:       c('🐸', 'animal', en('Frog', 'frogs', 'the frog'), he('צפרדע', 'הצפרדע', 'לצפרדע'),
                ru('Лягушка', 'лягушки', 'лягушек')),
  salmon:     c('🐟', 'animal', en('Salmon', 'salmon', 'the salmon'), he('סלמון', 'הסלמון', 'לסלמון'),
                ru('Лосось', 'лосося', 'лососей')),
  shark:      c('🦈', 'animal', en('Shark', 'sharks', 'the shark'), he('כריש', 'הכריש', 'לכריש'),
                ru('Акула', 'акулы', 'акул')),
  octopus:    c('🐙', 'animal', en('Octopus', 'octopuses', 'the octopus'), he('תמנון', 'התמנון', 'לתמנון'),
                ru('Осьминог', 'осьминога', 'осьминогов')),
  jellyfish:  c('🪼', 'animal', en('Jellyfish', 'jellyfish', 'the jellyfish'), he('מדוזה', 'המדוזה', 'למדוזה'),
                ru('Медуза', 'медузы', 'медуз')),
  coral:      c('🪸', 'animal', en('Coral', 'corals', 'the coral'), he('אלמוג', 'האלמוג', 'לאלמוג'),
                ru('Коралл', 'коралла', 'кораллов')),
  snail:      c('🐌', 'animal', en('Snail', 'snails', 'the snail'), he('חילזון', 'החילזון', 'לחילזון'),
                ru('Улитка', 'улитки', 'улиток')),
  lobster:    c('🦞', 'animal', en('Lobster', 'lobsters', 'the lobster'), he('לובסטר', 'הלובסטר', 'ללובסטר'),
                ru('Омар', 'омара', 'омаров')),
  crab:       c('🦀', 'animal', en('Crab', 'crabs', 'the crab'), he('סרטן', 'הסרטן', 'לסרטן'),
                ru('Краб', 'краба', 'крабов')),
  bee:        c('🐝', 'animal', en('Bee', 'bees', 'the bee'), he('דבורה', 'הדבורה', 'לדבורה'),
                ru('Пчела', 'пчелы', 'пчёл')),
  ant:        c('🐜', 'animal', en('Ant', 'ants', 'the ant'), he('נמלה', 'הנמלה', 'לנמלה'),
                ru('Муравей', 'муравья', 'муравьёв')),
  butterfly:  c('🦋', 'animal', en('Butterfly', 'butterflies', 'the butterfly'), he('פרפר', 'הפרפר', 'לפרפר'),
                ru('Бабочка', 'бабочки', 'бабочек')),
  mosquito:   c('🦟', 'animal', en('Mosquito', 'mosquitoes', 'the mosquito'), he('יתוש', 'היתוש', 'ליתוש'),
                ru('Комар', 'комара', 'комаров')),
  fly:        c('🪰', 'animal', en('Fly', 'flies', 'the fly'), he('זבוב', 'הזבוב', 'לזבוב'),
                ru('Муха', 'мухи', 'мух')),
  spider:     c('🕷️', 'animal', en('Spider', 'spiders', 'the spider'), he('עכביש', 'העכביש', 'לעכביש'),
                ru('Паук', 'паука', 'пауков')),
  scorpion:   c('🦂', 'animal', en('Scorpion', 'scorpions', 'the scorpion'), he('עקרב', 'העקרב', 'לעקרב'),
                ru('Скорпион', 'скорпиона', 'скорпионов')),
  mushroom:   c('🍄', 'fungus', en('Mushroom', 'mushrooms', 'the mushroom'), he('פטרייה', 'הפטרייה', 'לפטרייה'),
                ru('Гриб', 'гриба', 'грибов')),
  daisy:      c('🌼', 'plant', en('Daisy', 'daisies', 'the daisy'), he('חיננית', 'החיננית', 'לחיננית'),
                ru('Маргаритка', 'маргаритки', 'маргариток')),
  sunflower:  c('🌻', 'plant', en('Sunflower', 'sunflowers', 'the sunflower'), he('חמנייה', 'החמנייה', 'לחמנייה'),
                ru('Подсолнух', 'подсолнуха', 'подсолнухов')),
  lettuce:    c('🥬', 'plant', en('Lettuce', 'lettuce', 'lettuce'), he('חסה', 'החסה', 'לחסה'),
                ru('Салат', 'салата')),
  carrot:     c('🥕', 'plant', en('Carrot', 'carrots', 'the carrot'), he('גזר', 'הגזר', 'לגזר'),
                ru('Морковь', 'моркови')),
  coffee:     c('☕', 'plant', en('Coffee', 'coffee plants', 'coffee'), he('קפה', 'הקפה', 'לקפה'),
                ru('Кофе', 'кофе')),
  olive:      c('🫒', 'plant', en('Olive', 'olives', 'the olive'), he('זית', 'הזית', 'לזית'),
                ru('Олива', 'оливы', 'олив')),
  tomato:     c('🍅', 'plant', en('Tomato', 'tomatoes', 'the tomato'), he('עגבנייה', 'העגבנייה', 'לעגבנייה'),
                ru('Помидор', 'помидора', 'помидоров')),
  potato:     c('🥔', 'plant', en('Potato', 'potatoes', 'the potato'), he('תפוח אדמה', 'תפוח האדמה', 'לתפוח האדמה'),
                ru('Картофель', 'картофеля')),
  eggplant:   c('🍆', 'plant', en('Eggplant', 'eggplants', 'the eggplant'), he('חציל', 'החציל', 'לחציל'),
                ru('Баклажан', 'баклажана', 'баклажанов')),
  chili:      c('🌶️', 'plant', en('Chili pepper', 'chili peppers', 'the chili pepper'), he('פלפל חריף', 'הפלפל החריף', 'לפלפל החריף'),
                ru('Перец чили', 'перца чили')),
  sweetpotato: c('🍠', 'plant', en('Sweet potato', 'sweet potatoes', 'the sweet potato'), he('בטטה', 'הבטטה', 'לבטטה'),
                 ru('Батат', 'батата')),
  kiwi:       c('🥝', 'plant', en('Kiwifruit', 'kiwifruit', 'the kiwifruit'), he('קיווי', 'הקיווי', 'לקיווי'),
                ru('Киви', 'киви')),
  blueberry:  c('🫐', 'plant', en('Blueberry', 'blueberries', 'the blueberry'), he('אוכמנית', 'האוכמנית', 'לאוכמנית'),
                ru('Голубика', 'голубики')),
  cactus:     c('🌵', 'plant', en('Cactus', 'cacti', 'the cactus'), he('קקטוס', 'הקקטוס', 'לקקטוס'),
                ru('Кактус', 'кактуса', 'кактусов')),
  pine:       c('🌲', 'plant', en('Pine', 'pines', 'the pine'), he('אורן', 'האורן', 'לאורן'),
                ru('Сосна', 'сосны', 'сосен')),
  avocado:    c('🥑', 'plant', en('Avocado', 'avocados', 'the avocado'), he('אבוקדו', 'האבוקדו', 'לאבוקדו'),
                ru('Авокадо', 'авокадо')),
  rose:       c('🌹', 'plant', en('Rose', 'roses', 'the rose'), he('ורד', 'הוורד', 'לוורד'),
                ru('Роза', 'розы', 'роз')),
  strawberry: c('🍓', 'plant', en('Strawberry', 'strawberries', 'the strawberry'), he('תות', 'התות', 'לתות'),
                ru('Клубника', 'клубники')),
  apple:      c('🍎', 'plant', en('Apple', 'apples', 'the apple'), he('תפוח', 'התפוח', 'לתפוח'),
                ru('Яблоня', 'яблони', 'яблонь')),
  cherry:     c('🍒', 'plant', en('Cherry', 'cherries', 'the cherry'), he('דובדבן', 'הדובדבן', 'לדובדבן'),
                ru('Черешня', 'черешни')),
  peach:      c('🍑', 'plant', en('Peach', 'peaches', 'the peach'), he('אפרסק', 'האפרסק', 'לאפרסק'),
                ru('Персик', 'персика', 'персиков')),
  cucumber:   c('🥒', 'plant', en('Cucumber', 'cucumbers', 'the cucumber'), he('מלפפון', 'המלפפון', 'למלפפון'),
                ru('Огурец', 'огурца', 'огурцов')),
  melon:      c('🍈', 'plant', en('Melon', 'melons', 'the melon'), he('מלון', 'המלון', 'למלון'),
                ru('Дыня', 'дыни', 'дынь')),
  pea:        c('🫛', 'plant', en('Pea', 'peas', 'the pea'), he('אפונה', 'האפונה', 'לאפונה'),
                ru('Горох', 'гороха')),
  peanut:     c('🥜', 'plant', en('Peanut', 'peanuts', 'the peanut'), he('בוטן', 'הבוטן', 'לבוטן'),
                ru('Арахис', 'арахиса')),
  chestnut:   c('🌰', 'plant', en('Chestnut', 'chestnuts', 'the chestnut'), he('ערמון', 'הערמון', 'לערמון'),
                ru('Каштан', 'каштана', 'каштанов')),
  watermelon: c('🍉', 'plant', en('Watermelon', 'watermelons', 'the watermelon'), he('אבטיח', 'האבטיח', 'לאבטיח'),
                ru('Арбуз', 'арбуза', 'арбузов')),
  orange:     c('🍊', 'plant', en('Orange', 'oranges', 'the orange'), he('תפוז', 'התפוז', 'לתפוז'),
                ru('Апельсин', 'апельсина', 'апельсинов')),
  lemon:      c('🍋', 'plant', en('Lemon', 'lemons', 'the lemon'), he('לימון', 'הלימון', 'ללימון'),
                ru('Лимон', 'лимона', 'лимонов')),
  mango:      c('🥭', 'plant', en('Mango', 'mangoes', 'the mango'), he('מנגו', 'המנגו', 'למנגו'),
                ru('Манго', 'манго')),
  maple:      c('🍁', 'plant', en('Maple', 'maples', 'the maple'), he('אדר', 'האדר', 'לאדר'),
                ru('Клён', 'клёна', 'клёнов')),
  choc:       c('🍫', 'plant', en('Chocolate', 'cocoa trees', 'chocolate'), he('שוקולד', 'השוקולד', 'לשוקולד'),
                ru('Шоколад', 'какао')),
  hibiscus:   c('🌺', 'plant', en('Hibiscus', 'hibiscus', 'the hibiscus'), he('היביסקוס', 'ההיביסקוס', 'להיביסקוס'),
                ru('Гибискус', 'гибискуса', 'гибискусов')),
  broccoli:   c('🥦', 'plant', en('Broccoli', 'broccoli', 'broccoli'), he('ברוקולי', 'הברוקולי', 'לברוקולי'),
                ru('Брокколи', 'брокколи')),
  grape:      c('🍇', 'plant', en('Grapes', 'grapes', 'the grape'), he('ענבים', 'הענבים', 'לענבים'),
                ru('Виноград', 'винограда')),
  tulip:      c('🌷', 'plant', en('Tulip', 'tulips', 'the tulip'), he('צבעוני', 'הצבעוני', 'לצבעוני'),
                ru('Тюльпан', 'тюльпана', 'тюльпанов')),
  palm:       c('🌴', 'plant', en('Palm', 'palms', 'the palm'), he('דקל', 'הדקל', 'לדקל'),
                ru('Пальма', 'пальмы', 'пальм')),
  banana:     c('🍌', 'plant', en('Banana', 'bananas', 'the banana'), he('בננה', 'הבננה', 'לבננה'),
                ru('Банан', 'банана', 'бананов')),
  ginger:     c('🫚', 'plant', en('Ginger', 'ginger', 'ginger'), he("ג'ינג'ר", "הג'ינג'ר", "לג'ינג'ר"),
                ru('Имбирь', 'имбиря')),
  pineapple:  c('🍍', 'plant', en('Pineapple', 'pineapples', 'the pineapple'), he('אננס', 'האננס', 'לאננס'),
                ru('Ананас', 'ананаса', 'ананасов')),
  rice:       c('🌾', 'plant', en('Rice', 'rice', 'rice'), he('אורז', 'האורז', 'לאורז'),
                ru('Рис', 'риса')),
  corn:       c('🌽', 'plant', en('Corn', 'corn', 'corn'), he('תירס', 'התירס', 'לתירס'),
                ru('Кукуруза', 'кукурузы')),
  bamboo:     c('🎋', 'plant', en('Bamboo', 'bamboo', 'bamboo'), he('במבוק', 'הבמבוק', 'לבמבוק'),
                ru('Бамбук', 'бамбука')),
};

/*
 * What a casual player lumps each creature with — its look, its habitat, the
 * aisle it is sold in — not what it is. Only the question generator reads
 * this (js/kin/generate.js): a question is hard when the wrong answer shares
 * more of these with the target than the right one does, as the shark does
 * with the whale and the hippo does not. The mushroom is tagged "plant" on
 * purpose; that is the belief the game exists to overturn.
 */
export const LOOKS = {
  you: 'human',
  gorilla: 'ape furry wild big', orangutan: 'ape furry wild',
  monkey: 'ape furry wild',
  mouse: 'furry small pet rodentlike', hamster: 'furry small pet rodentlike',
  rat: 'furry small rodentlike', squirrel: 'furry small wild rodentlike',
  beaver: 'furry water wild',
  rabbit: 'furry small pet rodentlike', hedgehog: 'furry small rodentlike wild',
  bat: 'furry small flyer night wild',
  cat: 'furry pet hunter', dog: 'furry pet hunter', bear: 'furry wild big hunter',
  lion: 'furry wild big hunter', tiger: 'furry wild big hunter striped', fox: 'furry wild hunter',
  panda: 'furry wild big', badger: 'furry wild night striped', skunk: 'furry wild night small striped',
  seal: 'sea water wild', raccoon: 'furry wild night striped', otter: 'furry water wild',
  horse: 'hoofed farm big', rhino: 'hoofed wild big horned', camel: 'hoofed farm big desert',
  zebra: 'hoofed wild striped', donkey: 'hoofed farm', llama: 'hoofed farm furry',
  pig: 'hoofed farm', giraffe: 'hoofed wild big', cow: 'hoofed farm big horned',
  sheep: 'hoofed farm furry', goat: 'hoofed farm horned', deer: 'hoofed wild horned',
  hippo: 'wild big water',
  whale: 'sea water big fishlike', dolphin: 'sea water fishlike',
  elephant: 'wild big trunk', mammoth: 'big trunk extinct',
  koala: 'furry wild climber', kangaroo: 'furry wild', sloth: 'furry wild climber',
  chicken: 'bird farm', turkey: 'bird farm', peacock: 'bird farm',
  duck: 'bird farm water', swan: 'bird wild water', flamingo: 'bird wild water',
  pigeon: 'bird flyer', dodo: 'bird extinct', penguin: 'bird sea water',
  eagle: 'bird flyer hunter wild', parrot: 'bird flyer pet', owl: 'bird flyer hunter wild night',
  trex: 'reptile extinct hunter big scaly', sauropod: 'reptile extinct big scaly',
  croc: 'reptile scaly water hunter',
  turtle: 'reptile shell water', gecko: 'reptile scaly small', snake: 'reptile scaly legless',
  frog: 'water small slimy',
  salmon: 'fish fishlike sea water', shark: 'fish fishlike sea water hunter',
  octopus: 'sea water', snail: 'shell slimy small',
  jellyfish: 'sea water slimy', coral: 'sea plant',
  lobster: 'sea shell seafood clawed', crab: 'sea shell seafood clawed',
  bee: 'bug flyer small', ant: 'bug small', butterfly: 'bug flyer small',
  mosquito: 'bug flyer small', fly: 'bug flyer small',
  spider: 'bug small eightlegs', scorpion: 'bug eightlegs desert clawed',
  mushroom: 'plant veg',
  daisy: 'plant flower', sunflower: 'plant flower', rose: 'plant flower red', tulip: 'plant flower',
  lettuce: 'plant veg leafy', broccoli: 'plant veg leafy', tomato: 'plant veg red',
  potato: 'plant veg root', sweetpotato: 'plant veg root', carrot: 'plant veg root',
  ginger: 'plant veg root spicy', chili: 'plant veg red spicy', eggplant: 'plant veg',
  cucumber: 'plant veg', pea: 'plant veg',
  peanut: 'plant nut', chestnut: 'plant nut tree',
  corn: 'plant grain veg', rice: 'plant grain', bamboo: 'plant tree',
  kiwi: 'plant fruit', blueberry: 'plant fruit berry', strawberry: 'plant fruit berry red',
  apple: 'plant fruit tree red', cherry: 'plant fruit tree red stone', peach: 'plant fruit tree stone',
  mango: 'plant fruit tree stone', olive: 'plant fruit tree stone', avocado: 'plant fruit tree',
  watermelon: 'plant fruit', melon: 'plant fruit', orange: 'plant fruit tree', lemon: 'plant fruit tree',
  grape: 'plant fruit', banana: 'plant fruit', pineapple: 'plant fruit',
  coffee: 'plant drink', choc: 'plant drink sweet tree',
  hibiscus: 'plant flower red',
  cactus: 'plant desert', maple: 'plant tree', palm: 'plant tree', pine: 'plant tree',
};

/*
 * One species stands for each creature wherever a name has to be looked up
 * elsewhere — Open Tree of Life for the topology check
 * (scripts/kin-check-opentree.mjs), and later photographs and credits. The
 * choice matters: the game's "gecko" is a gecko, and which lizard you pick
 * changes where a snake meets it.
 */
export const SPECIES = {
  you: 'Homo sapiens', gorilla: 'Gorilla gorilla', orangutan: 'Pongo abelii', monkey: 'Macaca mulatta',
  mouse: 'Mus musculus', rat: 'Rattus norvegicus', hamster: 'Mesocricetus auratus',
  squirrel: 'Sciurus vulgaris', beaver: 'Castor fiber', rabbit: 'Oryctolagus cuniculus',
  hedgehog: 'Erinaceus europaeus', bat: 'Rousettus aegyptiacus',
  cat: 'Felis catus', lion: 'Panthera leo', tiger: 'Panthera tigris',
  dog: 'Canis lupus', fox: 'Vulpes vulpes', bear: 'Ursus arctos', panda: 'Ailuropoda melanoleuca',
  seal: 'Phoca vitulina', raccoon: 'Procyon lotor', otter: 'Lutra lutra', badger: 'Meles meles',
  skunk: 'Mephitis mephitis',
  horse: 'Equus caballus', zebra: 'Equus quagga', donkey: 'Equus asinus', rhino: 'Ceratotherium simum',
  camel: 'Camelus dromedarius', llama: 'Lama glama', pig: 'Sus scrofa',
  giraffe: 'Giraffa camelopardalis', deer: 'Cervus elaphus', cow: 'Bos taurus', sheep: 'Ovis aries',
  goat: 'Capra hircus', hippo: 'Hippopotamus amphibius', whale: 'Balaenoptera musculus',
  dolphin: 'Tursiops truncatus', elephant: 'Loxodonta africana', mammoth: 'Mammuthus primigenius',
  sloth: 'Bradypus variegatus', koala: 'Phascolarctos cinereus', kangaroo: 'Macropus giganteus',
  chicken: 'Gallus gallus', turkey: 'Meleagris gallopavo', peacock: 'Pavo cristatus',
  duck: 'Anas platyrhynchos', swan: 'Cygnus olor', flamingo: 'Phoenicopterus roseus',
  pigeon: 'Columba livia', dodo: 'Raphus cucullatus', penguin: 'Aptenodytes forsteri',
  eagle: 'Aquila chrysaetos', parrot: 'Ara macao', owl: 'Bubo bubo',
  trex: 'Tyrannosaurus rex', sauropod: 'Brontosaurus excelsus', croc: 'Crocodylus porosus',
  turtle: 'Chelonia mydas', gecko: 'Hemidactylus turcicus', snake: 'Python bivittatus',
  frog: 'Rana temporaria', salmon: 'Salmo salar', shark: 'Carcharodon carcharias',
  octopus: 'Octopus vulgaris', snail: 'Cornu aspersum', jellyfish: 'Aurelia aurita',
  coral: 'Acropora millepora',
  lobster: 'Homarus americanus', crab: 'Callinectes sapidus', bee: 'Apis mellifera',
  ant: 'Formica rufa', butterfly: 'Danaus plexippus', mosquito: 'Aedes aegypti',
  fly: 'Musca domestica', spider: 'Araneus diadematus', scorpion: 'Centruroides sculpturatus',
  mushroom: 'Agaricus bisporus',
  daisy: 'Bellis perennis', sunflower: 'Helianthus annuus', lettuce: 'Lactuca sativa',
  carrot: 'Daucus carota', coffee: 'Coffea arabica', olive: 'Olea europaea',
  tomato: 'Solanum lycopersicum', potato: 'Solanum tuberosum', eggplant: 'Solanum melongena',
  chili: 'Capsicum annuum', sweetpotato: 'Ipomoea batatas',
  kiwi: 'Actinidia chinensis', blueberry: 'Vaccinium corymbosum', cactus: 'Carnegiea gigantea',
  rose: 'Rosa canina', strawberry: 'Fragaria vesca', apple: 'Malus domestica',
  cherry: 'Prunus avium', peach: 'Prunus persica',
  cucumber: 'Cucumis sativus', melon: 'Cucumis melo', watermelon: 'Citrullus lanatus',
  pea: 'Pisum sativum', peanut: 'Arachis hypogaea',
  chestnut: 'Castanea sativa',
  orange: 'Citrus sinensis', lemon: 'Citrus limon', mango: 'Mangifera indica', maple: 'Acer saccharum',
  choc: 'Theobroma cacao', hibiscus: 'Hibiscus rosa-sinensis', broccoli: 'Brassica oleracea',
  grape: 'Vitis vinifera', pine: 'Pinus sylvestris', avocado: 'Persea americana',
  tulip: 'Tulipa gesneriana', palm: 'Phoenix dactylifera', banana: 'Musa acuminata',
  ginger: 'Zingiber officinale', pineapple: 'Ananas comosus',
  rice: 'Oryza sativa', corn: 'Zea mays', bamboo: 'Phyllostachys edulis',
};
